#!/bin/bash

# Usage: $_SUB_NAME vts -a <goal> [-h <vts_dir>] [-Dopt1 -Dopt2 ...]
# Summary: Command line manager for vts
# Group: Ingg
#
# Help: Command line wrapper for vts application
#
#   -a : the action for the vts [option: start | stop | restart]
#
#   Optional:
#      -h : vts installation directory
#      -v : Print output
#

source $_SUB_ROOT/share/utils/print.sh
source $_SUB_ROOT/share/vts/vts.properties

debug="false"
action=""
vtsRoot="$vts_root"
options=""

while getopts "a:v" optname
do
    case "$optname" in
        "h")
            vtsRoot=$OPTARG
        ;;
        "a")
            action=$OPTARG
        ;;
        "v")
            debug="true"
        ;;
        "?")
            echo "Unknown option $OPTARG"
            exit 1
            ;;
        ":")
            echo "No argument value for option $OPTARG"
            exit 1
            ;;
        *)
            # Should not occur
            echo "Unknown error while processing options"
        ;;
    esac
done

if [ "$action" = "" ]; then
    println_error "You must specify a action"
    $_SUB_NAME help vts
    exit 1
fi

if [ "$action" != "start" ] && [ "$action" != "stop" ] && [ "$action" != "restart" ]; then
    println_error "Action not supported"
    $_SUB_NAME help vts
    exit 1
fi

if [ "$vtsRoot" = "" ]; then
    println_error "You must specify the vts installation directory"
    $_SUB_NAME help vts
    exit 1
fi

if [ "$action" = "start" ]; then
    command="(cd $vtsRoot && bin/startup.sh -clean -debug &)"

elif [ "$action" = "stop" ]; then
    command="(cd $vtsRoot && bin/shutdown.sh &)"

else
    command="(cd $vtsRoot && touch pickup/corehub-reference-deployment.plan)"
fi

if [[ $debug == "false" ]]; then
   commandOutput="> /dev/null 2>&1"
fi

# Build the application
echo "Executing command: $command"
eval $command $commandOutput

if [[ "$?" != "0" ]]; then
    println_error "Error executing vts action"
    exit 4
fi

println_success "$action vts action applied successfuly"

if command -v "say" | grep "say" &>/dev/null; then
    say "$action vts action applied successfuly"
fi
