#!/usr/bin/env ruby

# Usage: $_SUB_NAME rgit <command>
# Summary: Execute a git command on all the sub directories
# Help: For each directory execute the git command
# Group: Env
#
#  Options:
#    -o | --oneline: oneline output by repository
#
#  Examples:
#
#  * $_SUB_NAME rgit fetch
#  * $_SUB_NAME rgit pull --rebase

onelineOutput = false

args = []
ARGV.each do |x|
    if x == "-o" || x == '--oneline'
        onelineOutput = true
    else
        args.push(x)
    end
end

args = args.join(" ")

Dir.foreach('.') do |f|
    next unless File.directory? f #only dirs
    next if f =~ /\.+/  #skip . and ..

    Dir.chdir(f) do |dir|
        if Dir.new('.').include?('.git')

            output = `git #{args} 2>&1`

            unless output.empty? && $?.success?
                if !onelineOutput
                    puts dir
                    puts "-"*dir.size
                    puts output
                    puts "\n"
                else
                    print dir, ": ", output.gsub("\n", ""), "\n"
                end
            end
        end

    end
end
