#!/bin/bash

# Usage: $_SUB_NAME mvn-3rdparty
# Summary: Update 3rd party libraries
# Group: Ingg virgo
#
# Help: Update 3rd party libraries
#

source $_SUB_ROOT/share/utils/print.sh
source $_SUB_ROOT/share/virgo/virgo.properties

debug="false"
virgoRoot="$virgo_root"

while getopts "v" optname
do
    case "$optname" in
        "v")
            debug="true"
        ;;
        "?")
            echo "Unknown option $OPTARG"
            exit 1
            ;;
        ":")
            echo "No argument value for option $OPTARG"
            exit 1
            ;;
        *)
            # Should not occur
            echo "Unknown error while processing options"
        ;;
    esac
done

if [ "$virgoRoot" = "" ]; then
    println_error "You must specify the virgo installation directory"
    $_SUB_NAME help mvn-virgo
    exit 1
fi

mavenCommand="mvn -s ~/projects/company/enear/inspire/confs/maven-settings.xml \
    -f $corehub_repo_dir/corehub-3rdparty-repository/pom.xml clean install"

mavenOutput=""

if [[ $debug == "false" ]]; then
   mavenOutput="> /dev/null 2>&1"
fi

# Build the application
echo "Executing maven plugin: $mavenCommand"
eval $mavenCommand $mavenOutput

if [[ "$?" != "0" ]]; then
    println_error "Error executing maven virgo goal"
    exit 4
fi

cp $corehub_repo_dir/corehub-3rdparty-repository/target/classes/usr/local/vts/repository/3rdparty/*.jar \
        $virgo_root/repository/3rdparty

println_success "3rd party copied successfuly"

if command -v "say" | grep "say" &>/dev/null; then
    say "Virgo goal applied successfuly"
fi
