#!/bin/bash

# Usage: $_SUB_NAME vts-3rdparty
# Summary: Update 3rd party libraries
# Group: Ingg
#
# Help: Update 3rd party libraries
#

source $_SUB_ROOT/share/utils/print.sh
source $_SUB_ROOT/share/vts/vts.properties

debug="false"
vtsRoot="$vts_root"

while getopts "v" optname
do
    case "$optname" in
        "v")
            debug="true"
        ;;
        "?")
            echo "Unknown option $OPTARG"
            exit 1
            ;;
        ":")
            echo "No argument value for option $OPTARG"
            exit 1
            ;;
        *)
            # Should not occur
            echo "Unknown error while processing options"
        ;;
    esac
done

if [ "$vtsRoot" = "" ]; then
    println_error "You must specify the vts installation directory"
    $_SUB_NAME help mvn-vts
    exit 1
fi

println_info "Updating vts 3rdparty libraries"

mavenCommand="mvn -s ~/projects/company/enear/inspire/confs/maven-settings.xml\
 -f $corehub_repo_dir/corehub-ui-3rdparty-repository/pom.xml clean install"

mavenOutput=""

if [[ $debug == "false" ]]; then
   mavenOutput="> /dev/null 2>&1"
fi

# Build the application
echo "Executing maven command:"
echo "> $mavenCommand"
eval $mavenCommand $mavenOutput

if [[ "$?" != "0" ]]; then
    println_error "Error executing vts 3rdparty"
    exit 4
fi

rm -rf  $vts_root/repository/3rdparty/*

if [ ! -d $vts_root/repository/3rdparty ]; then
    mkdir $vts_root/repository/3rdparty
fi

cp $corehub_repo_dir/corehub-ui-3rdparty-repository/target/classes/usr/share/vts/repository/3rdparty/*.jar \
        $vts_root/repository/3rdparty

println_success "3rd party copied successfuly"

if command -v "say" | grep "say" &>/dev/null; then
    say "vts goal applied successfuly"
fi
